# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15f5d7e29fda592746fac146396477ac90810b5e1d241769d16947e9d0d5098fb41d657fab788ee6b4d9b5e0035f809ecb7e875b9e0806d1f73e6d4ce265d5ce

test:
  secret_key_base: 9ca848aba04cdb875804fcc2097a4267d5c89acb0582cc8d989898a7ce92867776760bb8e338058c47196080f7c046546eef92ade53068a77ee7f5d11044f881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
